### ISSUE TITLE
Grid doesnt show first record in records binding.

### ISSUE THREAD

**Issue by combinedit** [codaxy/cx-starter-kit#2]
I followed the blog post which used scaffolding.

----GRID CODE----
`  <Grid records:bind="$page.points"
              style="flex:1"
              scrollable
              columns={[
                      {field: 'date', header: 'Date'},
                      {field: 'location', header: 'Location'},
                      {field: 'speed', header: 'Speed', align: 'right'},
                      {field: 'reason', header: 'Reason'},
                      {field: 'driver', header: 'Driver'},
              ]} />`

---Controller----
`this.store.set('$page.points', [{
            date: '2015-03-12 10:01:05',
            location: 'Smith Street, Darwin',
            speed: 10,
            reason: 'Track',
            driver: 'Mike Davis'
        },
            {
                date: '2015-03-12 10:01:05',
                location: 'Smith Street, Darwin',
                speed: 10,
                reason: 'Track',
                driver: 'Mike Davis'
            },
            {
                date: '2015-03-12 10:01:05',
                location: 'Smith Street, Darwin',
                speed: 10,
                reason: 'Track',
                driver: 'Mike Davis'
            }]);`
---SCREENSHOT---
![image](https://cloud.githubusercontent.com/assets/2665713/20412199/5a8d6ee0-ad79-11e6-95bd-3af6270bb0a8.png)

**Comment by mstijak** [comment]
If you scrollable, the grid must have a height. You should explicitly assign the height or make sure that the parent flexbox works and gives height to the grid.

http://cx.codaxy.com/fiddle/?f=tvsT57Dr
