### ISSUE TITLE
npm start issue.

### ISSUE THREAD

**Issue by spsenthil** [codaxy/cx-starter-kit#3]
Getting the following error after clone - npm instatll - npm start

index.js:1 Uncaught Error: Module build failed: Error: Couldn't find preset "babel-preset-env" relative to directory "/Users/dcteam/Documents/GitRepo/CXJS/cx-starter-kit/node_modules/babel-preset-cx-env" (While processing preset: "/Users/dcteam/Documents/GitRepo/CXJS/cx-starter-kit/node_modules/babel-preset-cx-env/index.js")

**Comment by mstijak** [comment]
Oh. Thanks for reporting. `npm install babel-preset-env` will fix the issue.

**Comment by spsenthil** [comment]
npm install babel-pret-env --save solved . Thanks a lot.
